name: Update DSA Stats Card

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dsa-stats-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Generate custom SVG card
        run: python3 generate_card.py

      - name: Force Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add codolio-stats.svg
          git commit -m "Update Codolio stats card $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force origin HEAD:dsaStats
